services:
  mangodb:
    image: mongo:latest

    container_name: mangodb

    ports:
      - "27007:27017"

    volumes:
      - ./mangodb:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWARD=${MONGO_INITDB_ROOT_PASSWARD}

    networks:
      - backend

    restart: always

networks:
  backend:

